name: Build BTLEmap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build
        run: |
          xcodebuild \
            -project BLE-Scanner.xcodeproj \
            -scheme BLE-Scanner \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build